//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dulyojuke.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dulyojuke.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] CircularProgressBar {
            get {
                object obj = ResourceManager.GetObject("CircularProgressBar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;CircularProgressBar&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:CircularProgressBar.CircularProgressBar&quot;&gt;
        ///            &lt;summary&gt;
        ///                The circular progress bar windows form control
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:CircularProgressBar.CircularProgressBar.#ctor&quot;&gt;
        ///            &lt;summary&gt;
        ///                Initializes a new instance of the &lt;see cref=&quot;T:CircularProgressBar.CircularProgress[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CircularProgressBar1 {
            get {
                return ResourceManager.GetString("CircularProgressBar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Gear {
            get {
                object obj = ResourceManager.GetObject("Gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] MediaToolkit {
            get {
                object obj = ResourceManager.GetObject("MediaToolkit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;configuration&gt;
        ///   &lt;runtime&gt;
        ///      &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///       &lt;dependentAssembly&gt;
        ///         &lt;assemblyIdentity name=&quot;taglib-sharp&quot; publicKeyToken=&quot;db62eba44689b5b0&quot; /&gt;
        ///         &lt;bindingRedirect oldVersion=&quot;2.0.0.0-2.1.0.0&quot; newVersion=&quot;2.1.0.0&quot;/&gt;
        ///       &lt;/dependentAssembly&gt;
        ///      &lt;/assemblyBinding&gt;
        ///   &lt;/runtime&gt;
        ///&lt;/configuration&gt;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string policy_2_0_taglib_sharp {
            get {
                return ResourceManager.GetString("policy_2_0_taglib_sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] policy_2_0_taglib_sharp1 {
            get {
                object obj = ResourceManager.GetObject("policy_2_0_taglib_sharp1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] taglib_sharp {
            get {
                object obj = ResourceManager.GetObject("taglib_sharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] WinFormAnimation {
            get {
                object obj = ResourceManager.GetObject("WinFormAnimation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;WinFormAnimation&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:WinFormAnimation.Animator&quot;&gt;
        ///            &lt;summary&gt;
        ///                The one dimensional animator class, useful for animating raw values
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;T:WinFormAnimation.Animator.KnownProperties&quot;&gt;
        ///            &lt;summary&gt;
        ///                The known one dimensional properties of WinForm controls
        ///            &lt;/summary&gt;
        /// [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WinFormAnimation1 {
            get {
                return ResourceManager.GetString("WinFormAnimation1", resourceCulture);
            }
        }
    }
}
